// <auto-generated />
using System;
using Ballware.Storage.Data.Ef.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ballware.Storage.Data.Ef.SqlServer.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20250702153916_UniqueAttachmentFileName")]
    partial class UniqueAttachmentFileName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ballware.Storage.Data.Persistables.Attachment", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creator_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("entity");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_changer_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique();

                    b.HasIndex("TenantId", "Entity", "OwnerId", "FileName")
                        .IsUnique();

                    b.ToTable("attachment");
                });

            modelBuilder.Entity("Ballware.Storage.Data.Persistables.Temporary", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique();

                    b.ToTable("temporary");
                });
#pragma warning restore 612, 618
        }
    }
}
