name: Docker Image Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ballware.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/.
          file: src/Ballware.Storage.Service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ballware.azurecr.io/ballware-storage-service:${{github.ref_name}}  