name: Docker Image Latest

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ballware.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_TOKEN }}      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 
            8.0
      - name: Install SonarQube
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Start SonarQube scan
        run: dotnet sonarscanner begin /k:"ballware_ballware-storage-service" /o:"ballware" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Build solution for SonarQube
        run: dotnet build ballware-storage-service.sln --no-incremental
      - name: End SonarQube scan
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/.
          file: src/Ballware.Storage.Service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ballware.azurecr.io/ballware-storage-service:latest  