name: Publish packages and images
on:
  push:
    branches:
      - main
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0   
      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool
      - name: Install swashbuckle CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 7.2.0
      - name: Install nswag CLI
        run: dotnet tool install --global Nswag.ConsoleCore
      - name: Fetch GitVersion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Restore dependencies
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/ballware/index.json" \
            --name github \
            --username frankball \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text
          dotnet restore ballware-storage-service.sln
      - name: Build solution
        run: |
          dotnet build ballware-storage-service.sln -p:Version=${{ env.GitVersion_SemVer }} --configuration Release   
      - name: Generate Swagger specification
        working-directory: src/Ballware.Storage.Service
        env:
          ASPNETCORE_ENVIRONMENT: Swagger
        run: |
          swagger tofile \
            --output ../Ballware.Storage.Service.Client/swagger.json \
            ./bin/Release/net8.0/Ballware.Storage.Service.dll \
            service
      - name: Generate service client code
        working-directory: src/Ballware.Storage.Service.Client
        run: |
          nswag run nswag.json
      - name: Pack NuGet packages
        run: |          
          dotnet pack ballware-storage-service.sln -p:Version=${{ env.GitVersion_SemVer }} --configuration Release --output ./nupkgs
      - name: Publish NuGet packages to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --source https://nuget.pkg.github.com/ballware/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: Create version tag on release
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ env.GitVersion_SemVer }}
          git push origin refs/tags/v${{ env.GitVersion_SemVer }} refs/heads/main
      - name: Set environment variables for Docker tags
        run: |
          echo "DOCKER_TAG=${{ env.GitVersion_SemVer }}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "DOCKER_TAG2=stable" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG2=latest" >> $GITHUB_ENV
          fi      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: src/.
          file: src/Ballware.Storage.Service/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            ghcr.io/ballware/ballware-storage-service:${{ env.DOCKER_TAG }}
            ghcr.io/ballware/ballware-storage-service:${{ env.DOCKER_TAG2 }}      
