name: Analyse SonarQube Latest

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 
            8.0          
      - name: Install SonarQube
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Install dotCover
        run: dotnet tool install --global JetBrains.dotCover.GlobalTool
      - name: Start SonarQube scan
        run: dotnet sonarscanner begin /k:"ballware_ballware-storage-service" /o:"ballware" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths="dotCover.PreCommit.html,dotCover.Output.html"
      - name: Build solution for SonarQube
        run: dotnet build ballware-storage-service.sln --no-incremental
      - name: Run tests with coverage report        
        run: dotnet dotcover test ballware-storage-service.sln --dcReportType=HTML -- NUnit.Where="cat == UnitTest"
      - name: End SonarQube scan
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" 
