name: Analyse SonarQube Latest

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 
            8.0          
      - name: Install SonarQube
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Install dotnet coverage
        run: dotnet tool install --global dotnet-coverage        
      #- name: Start SonarQube scan
      #  run: dotnet sonarscanner begin /k:"ballware_ballware-storage-service" /o:"ballware" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
      - name: Build solution for SonarQube
        run: dotnet build ballware-storage-service.sln --no-incremental
      - name: Run tests with coverage report
        run: dotnet test --no-build --collect:"Code Coverage;Format=Xml;CoverageFileName=coverage.xml" -v detailed   
      #- name: End SonarQube scan
      #  run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"        
